package models

//go:generate go run ../../../scripts/generate_all_models.go

/* -~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- */
/*            - DB Models -            */
/* -~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- */

// All DB Models should implement this.
type Model interface {
	TableName() string
}

// Auto-generated by scripts/generate_all_models. DO NOT EDIT.

// AllModels is a list of all models to be migrated.
// Code generated by generate_all_models.go; DO NOT EDIT.
var AllModels = []interface{}{
	&GPTChat{},
	&GPTMessage{},
	&Group{},
	&User{},
	&UsersInGroup{},
}
