name: Push to Master 🔥

on:
  push:
    branches: [master] # — Triggers on push to master
  pull_request:
    branches: [master] # — Triggers on PR to master

jobs:
  push-to-master:
    runs-on: ubuntu-latest
    steps:
      - name: "[ 1️⃣ — Checkout GitHub Repository]"
        uses: actions/checkout@v4

      - name: "[ 2️⃣ — Setup Go v1.23]"
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: "[ 3️⃣ — Download & Cache Go Modules]"
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: "[ 4️⃣ — Run Tests with Coverage]"
        run: go test ./... -race -coverprofile=coverage.txt

      - name: "[ 5️⃣ — Upload Coverage File to Codecov]"
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: gilperopiola/grpc-gateway-impl
          file: ./coverage.txt
