name: Deploy or PR to Master

on:
  push:
    branches: [ master ] # ---------------------------------------------------------- Triggers on push to master
  pull_request:
    branches: [ master ] # ---------------------------------------------------------- Triggers on PR to master

jobs:
  deploy-or-pr-to-master:
    runs-on: ubuntu-latest

    steps:
    - name: "[ - Checkout GitHub Repository - ]" # ---------------------------------- Checkout the repository 
      uses: actions/checkout@v2   
    
    - name: "[ - Setup Go - ]" # ---------------------------------------------------- Setup Go v1.20
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: "[ - Download and Cache Go Modules - ]" # ------------------------------- Cache Go mods download
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: "[ - Run Tests -> Create Coverage File - ]" # --------------------------- Run tests, create coverage.txt
      run: go test ./... --all -race -coverprofile=coverage.txt

    - name: "[ - Upload Coverage File to Codecov - ]" # ----------------------------- Upload coverage to codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: gilperopiola/grpc-gateway-impl
        file: ./coverage.txt

